### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by sosiska** [srimaln91/go-geom#38]
Hello!

I want to port some code from lua to Go.
Now I use this lib: https://github.com/tarantool/gis
As I see it, it uses the same libraries.

Here code on lua:
```lua
gis   = require('gis')

wgs84 = 4326
geocentric_wgs84 = 4328
zones = {"POLYGON ((36.6614036010865 56.3628653954021, 36.0873679565553 55.7357318093992, 36.6394309448365 55.1533993108445, 37.4222068237427 54.987911877815, 38.3203391479615 55.0636485766673, 38.809230749524 55.288429792929, 39.0344504760865 55.5680080456668, 39.149806921399 55.9058207554675, 38.4851340698365 56.301833846656, 37.831447546399 56.4785555392187, 37.216213171399 56.4572707398394, 36.6614036010865 56.3628653954021))"}

lon = 37.475
lat = 55.7125

point = gis.Point({lon, lat}, wgs84):transform(geocentric_wgs84)

for _, zone in zones do
   if gis.wkt.decode(zone, wgs84):transform(geocentric_wgs84):contains(point) then
      print("it is!")
   end
end
```
My problem now is that I can't convert GEOSGeom struct from wgs84 to geocentric_wgs84, can you please help me, bro?
Thanks.

**Comment by srimaln91** [comment]
HI,

I assume that you are using `go-geom` library.  Can you show me the Go code that you have written? It will help me to understand the actual problem.

Thanks.

**Comment by srimaln91** [comment]
#39

**Comment by sosiska** [comment]
> HI,
> 
> I assume that you are using `go-geom` library. Can you show me the Go code that you have written? It will help me to understand the actual problem.
> 
> Also, note that EPSG 4328 has been deprecated.
> https://epsg.io/4328
> 
> Thanks.

Here you are:
```go
package main

import (
	"fmt"

	"github.com/srimaln91/go-geom/geom"
)

func main() {
	var err error
	var pointGeom *geom.Geom
	if pointGeom, err = geom.CreateFromWKT("POINT (37.475 55.7125)"); err != nil {
		fmt.Println(err)
		return
	}

	wgs := "4326"
	wgsSphere := "4978"
	pointGeom.Project(wgs, wgsSphere)
}
```
Here I get panic.

When I try to transform same point in the lua library:
```lua
a = gis.Point({37.475, 55.7125}, 4326):transform(4978)

print(a)
```
 I get this result:
`POINT Z (2858087.451554609 2191106.95599294 5246475.953715225)`

**Comment by srimaln91** [comment]
Recently, I have done some updates to this library which will fix this issue. Give me a little bit amount of time. I will add them to the upstream.

**Comment by srimaln91** [comment]
Below is a working example. Please use v1.3.0

```go
package main

import (
	"fmt"

	"github.com/srimaln91/go-geom/geom"
)

func main() {
    var err error
    var pointGeom *geom.Geom

    if pointGeom, err = geom.CreateFromWKT("POINT (37.475 55.7125)"); err != nil {
        fmt.Println(err)
        return
    }

    wgs := geom.SRS["EPSG:4326"]
    wgsSphere := geom.SRS["EPSG:4978"]
    pointGeom.Project(wgs, wgsSphere)
    
    geoJSONOut, _ := pointGeom.ToGeoJSON(4,0)

    fmt.Println(geoJSONOut)

    //cleanup
    pointGeom.Free()
}

```

**Comment by sosiska** [comment]
Yes, seems it works, thanks!
But why i can't see 3rd coordinate? Like in lua output:
`POINT Z (2858087.451554609 2191106.95599294 5246475.953715225)`
